- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bash:
    ~/.bashrc:
    ~/.bash_profile:
    ~/bin:
    ~/.clojure:
    ~/.direnvrc:
    ~/.emacs.d:
      path: emacs-29.d
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.gnupg:
    ~/.irbrc:
    ~/.nvm:
    ~/.nvmrc:
    ~/.pyenv:
    ~/.pyenv/plugins/pyenv-virtualenv:
      path: pyenv-virtualenv
      create: false
      relink: false
    ~/qmk_firmware:
    ~/.rbenv:
    ~/.rbenv/plugins/ruby-build:
      path: ruby-build
      create: false
      relink: false
    ~/.shell:
    ~/.spacemacs:
    ~/.spacemacs-private:
    ~/.tmux:
    ~/.tmux.conf: tmux/tmux.conf
    ~/.vimrc:
    ~/.vim:
    ~/.zsh:
    ~/.zshrc:
    ~/.alacritty.toml:

- create:
    - ~/.pyenv/plugins/pyenv-virtualenv

- shell: 
  - [git submodule sync --recursive, Syncronize submodule remote Urls]
  - [git submodule update --init --recursive, Initialize/Update submodules] 
  - [brew bundle, Installing package from Brewfile]
  - [brew link gnupg@2.2, Linking GPG v2.2 (Temporary step)]
  - [./install-alacritty.sh, Building and installing Alacritty]
