- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bash:
    ~/.bashrc:
    ~/.bash_profile:
    ~/.clojure:
    ~/.direnvrc:
    ~/.emacs.d:
      path: new-emacs.d
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.irbrc:
    ~/.nvm:
    ~/.pyenv:
    ~/.pyenv/plugins/pyenv-virtualenv:
      path: pyenv-virtualenv
      create: false
      relink: false
    ~/qmk_firmware:
    ~/.rbenv:
    ~/.rbenv/plugins/ruby-build:
      path: ruby-build
      create: false
      relink: false
    ~/.shell:
    ~/.spacemacs:
    ~/.spacemacs-private:
    ~/.tmux:
    ~/.tmux.conf: tmux/tmux.conf
    ~/.zsh:
    ~/.zshrc:

- create:
    - ~/.rbenv/plugins/ruby-build
    - ~/.pyenv/plugins/pyenv-virtualenv

- shell: 
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - >
    git cleanall -f
    rbenv/plugins/
    shell/plugins/
    zsh/plugins/
