- defaults:
    link:
      relink: true
      create: true
    shell:
      stdout: true
      stderr: true
- clean: ['~']
- link:
    ~/.vimrc: vim/vimrc
    ~/.vim: vim/vim
    ~/.gitconfig: git/gitconfig
    ~/.bashrc: bash/bash.sh
    ~/.tmux.conf: tmux/tmux.conf
    ~/.tmux.reset.conf: tmux/tmux.reset.conf
- shell:
  -
    description: Updating git submodules..
    command: git submodule update --init --recursive ./

  -
    description: Fixing OSX's great bash config behavior
    command: if [[ $(uname -s) == "Darwin" ]]; then  echo "if [ -s ~/.bashrc ]; then source ~/.bashrc; fi" > ~/.bash_profile ; fi
