- defaults:
    link:
      relink: true
      create: true
- clean: ['~']
- link:
    ~/.vimrc: vim/vimrc
    ~/.vim: vim/vim
    ~/.gitconfig: git/gitconfig
    ~/.bashrc: bash/bash.sh
- shell:
  - [git submodule update --init --recursive vim/plugins]
