runtime plugins/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('plugins/{}')

nnoremap <leader>r :source ~/.vimrc<CR>

runtime config/general.vim
runtime config/airline.vim
runtime config/ctrlp.vim
runtime config/nerdtree.vim
runtime config/fugitive.vim
runtime config/neocomplete.vim
runtime config/ack.vim
runtime config/syntastic.vim
