# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#zmodload zsh/zprof  #debug startup time

if [ -d "/usr/share/powerline/bindings/bash" ]; then
    source /usr/share/powerline/bindings/bash/powerline.sh
elif [ -d "$HOME/.vim/plugged/powerline/powerline/bindings/bash/powerline.sh" ]; then
    source $HOME/.vim/plugged/powerline/powerline/bindings/bash/powerline.sh
fi

source $HOME/.zshrc.zplug.common

# load different zshrc/tmux config file depending on HOSTNAME
HOSTNAME=$(hostname)
if [[ $HOSTNAME == *"aws"* ]] || [[ $HOSTNAME == *"nec"* ]] || [[ $USER == "ec2-user" ]] ; then
    source $HOME/.zshrc.zplug.ssh
    ln -sf ~/.tmux.conf.ssh ~/.tmux.conf.local
elif [[ $HOSTNAME == *"brownfunk"* ]]; then
    source $HOME/.zshrc.zplug.bfunk
    ln -sf ~/.tmux.conf.ssh ~/.tmux.conf.local
elif [[ $HOSTNAME == *"-X202EP"* ]]; then
    source $HOME/.zshrc.zplug.bfunk
    ln -sf ~/.tmux.conf.ssh_laptop ~/.tmux.conf.local
else
    source $HOME/.zshrc.zplug.local
    ln -sf ~/.tmux.conf.laptop ~/.tmux.conf.local
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
if [ -d "$HOME/anaconda3" ]; then
    CONDA=$HOME/anaconda3
elif [ -d "$HOME/miniconda3" ]; then
    CONDA=$HOME/miniconda3
fi

__conda_setup="$('$CONDA/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$CONDA/etc/profile.d/conda.sh" ]; then
        . "$CONDA/etc/profile.d/conda.sh"
        export PATH="$CONDA/bin:$PATH"
    else
        export PATH="$CONDA/bin:$PATH"
    fi
fi

unset __conda_setup
export VIRTUALENVWRAPPER_PYTHON=$CONDA/bin/python
# <<< conda initialize <<<

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# thefuck
eval $(thefuck --alias)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


#zprof #debug startup time
